### ISSUE TITLE
most of streams in Facebook marketing not working good | update Facebook marketing API field to be appropriate with API 19

### ISSUE THREAD

**Issue by eslamaboushashaa** [airbytehq/PyAirbyte#103] opened 2024-03-05 20:00 UTC
I received an error message as some fields that I was trying to access do not exist in the Facebook API V-19.
 I got these fields

- age_targeting
- gender_targeting
- labels, location
- estimated_ad_recall_rate_lower_bound
- estimated_ad_recall_rate_upper_bound
-  estimated_ad_recallers_lower_bound 
- estimated_ad_recallers_upper_bound

**Full error** 
Error: 100, (#100) age_targeting, gender_targeting, labels, location, estimated_ad_recall_rate_lower_bound, estimated_ad_recall_rate_upper_bound, estimated_ad_recallers_lower_bound, estimated_ad_recallers_upper_bound are not valid for fields param after V19.0.

**Comment by aaronsteers** [comment] 2024-03-05 21:41
@eslamaboushashaa - Thanks very much for reporting this issue. As a first step, we will see if I can reproduce this error.

Do you have a PyAirbyte code sample that can share with us? It is helpful if you include the "config" entry - removing or redacting any secrets, of course. 

Thanks!

**Comment by aaronsteers** [comment] 2024-03-05 21:54
@eslamaboushashaa - It looks like we have an issue open for this:

- https://github.com/airbytehq/airbyte/issues/35334

cc @marcosmarxm

**Comment by aaronsteers** [comment] 2024-03-05 21:55
I found an open PR here:

- https://github.com/airbytehq/airbyte/pull/35746

**Comment by aaronsteers** [comment] 2024-03-05 21:57
Closing (dedupe), in favor of:

- https://github.com/airbytehq/airbyte/issues/35334

as primary.

Please upvote that issue to get updates, and/or re-open if this is still needed to be separately tracked.

Thanks again for logging. Hopefully will close out with successful resolution very soon.

**Closed** 2024-03-05 21:57 UTC
